version: '3'

services:
  postgres:
    image: 'postgres:12'
    container_name: 'java-postgres'
    environment:
      - 'POSTGRES_DB=repositories'
      - 'POSTGRES_USER=root'
      - 'POSTGRES_PASSWORD=root'

  app:
    build: ./
    container_name: 'java-app'
    ports:
      - 8080:8080
    env_file:
      .env
