spring:

  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/repositories
#    url: jdbc:postgresql://localhost:5432/repositories
    username: root
    password: root
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
    open-in-view: false
    generate-ddl: true

GithubUsername: octocat
GithubFrequencyGet: 1